import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/lib/providers/SessionProvider";
import { getServerSession } from "next-auth";
import { ThemeProvider } from "@/lib/providers/ThemeProvider";
import QueryProvider from "@/lib/providers/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  // session
}: Readonly<{
  children: React.ReactNode,
  // session: Session
}>) {

  const session = await getServerSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <SessionProvider session={session}>
            <ThemeProvider attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange>
              {children}
            </ThemeProvider>
          </SessionProvider>
        </QueryProvider>

      </body>
    </html>
  );
}
